window.esdocSearchIndex = [
  [
    "hoist-connector-twitter/src/views/edit.js~editform",
    "class/src/views/edit.js~EditForm.html",
    "<span>EditForm</span> <span class=\"search-result-import-path\">hoist-connector-twitter/src/views/edit.js</span>",
    "class"
  ],
  [
    "hoist-connector-twitter/src/connector.js~twitterconnector",
    "class/src/connector.js~TwitterConnector.html",
    "<span>TwitterConnector</span> <span class=\"search-result-import-path\">hoist-connector-twitter/src/connector.js</span>",
    "class"
  ],
  [
    "hoist-connector-twitter/src/poll.js~poll",
    "function/index.html#static-function-poll",
    "<span>poll</span> <span class=\"search-result-import-path\">hoist-connector-twitter/src/poll.js</span>",
    "function"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "",
    "test-file/tests/unit_tests/proxy_tests.js.html#lineNumber19",
    "Connector",
    "test"
  ],
  [
    "",
    "test-file/tests/unit_tests/proxy_tests.js.html#lineNumber24",
    "Connector functions",
    "test"
  ],
  [
    "",
    "test-file/tests/unit_tests/proxy_tests.js.html#lineNumber25",
    "Connector functions should have methods expected",
    "test"
  ],
  [
    "",
    "test-file/tests/integration_tests/auth_tests.js.html#lineNumber9",
    "authorization steps",
    "test"
  ],
  [
    "",
    "test-file/tests/integration_tests/auth_tests.js.html#lineNumber19",
    "authorization steps on first bounce",
    "test"
  ],
  [
    "",
    "test-file/tests/integration_tests/auth_tests.js.html#lineNumber56",
    "authorization steps on first bounce should receive a redirect",
    "test"
  ],
  [
    "",
    "test-file/tests/integration_tests/auth_tests.js.html#lineNumber53",
    "authorization steps on first bounce should save current step",
    "test"
  ],
  [
    "",
    "test-file/tests/integration_tests/auth_tests.js.html#lineNumber47",
    "authorization steps on first bounce should save request token",
    "test"
  ],
  [
    "",
    "test-file/tests/integration_tests/auth_tests.js.html#lineNumber50",
    "authorization steps on first bounce should save request token secret",
    "test"
  ],
  [
    "src/connector.js",
    "file/src/connector.js.html",
    "src/connector.js",
    "file"
  ],
  [
    "src/connector.js~twitterconnector#constructor",
    "class/src/connector.js~TwitterConnector.html#instance-constructor-constructor",
    "src/connector.js~TwitterConnector#constructor",
    "method"
  ],
  [
    "src/connector.js~twitterconnector#get",
    "class/src/connector.js~TwitterConnector.html#instance-method-get",
    "src/connector.js~TwitterConnector#get",
    "method"
  ],
  [
    "src/connector.js~twitterconnector#post",
    "class/src/connector.js~TwitterConnector.html#instance-method-post",
    "src/connector.js~TwitterConnector#post",
    "method"
  ],
  [
    "src/poll.js",
    "file/src/poll.js.html",
    "src/poll.js",
    "file"
  ],
  [
    "src/views/edit.js",
    "file/src/views/edit.js.html",
    "src/views/edit.js",
    "file"
  ],
  [
    "src/views/edit.js~editform#browse",
    "class/src/views/edit.js~EditForm.html#instance-method-browse",
    "src/views/edit.js~EditForm#browse",
    "method"
  ],
  [
    "src/views/edit.js~editform#connect",
    "class/src/views/edit.js~EditForm.html#instance-method-connect",
    "src/views/edit.js~EditForm#connect",
    "method"
  ],
  [
    "src/views/edit.js~editform#constructor",
    "class/src/views/edit.js~EditForm.html#instance-constructor-constructor",
    "src/views/edit.js~EditForm#constructor",
    "method"
  ],
  [
    "src/views/edit.js~editform#render",
    "class/src/views/edit.js~EditForm.html#instance-method-render",
    "src/views/edit.js~EditForm#render",
    "method"
  ],
  [
    "src/views/edit.js~editform#state",
    "class/src/views/edit.js~EditForm.html#instance-member-state",
    "src/views/edit.js~EditForm#state",
    "member"
  ],
  [
    "tests/integration_tests/auth_tests.js",
    "test-file/tests/integration_tests/auth_tests.js.html",
    "tests/integration_tests/auth_tests.js",
    "testFile"
  ],
  [
    "tests/unit_tests/proxy_tests.js",
    "test-file/tests/unit_tests/proxy_tests.js.html",
    "tests/unit_tests/proxy_tests.js",
    "testFile"
  ]
]